spring:
  data:
    rest:
      base-path: /api/v1/dict
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${JPA_SHOW_SQL:false}
    show-sql: ${JPA_SHOW_SQL:false}
  application:
    name: Planista
server:
  error:
    include-message: ${SERVER_SHOW_ERROR:never}
    include-binding-errors: ${SERVER_SHOW_ERROR:never}
  port: ${APP_PORT:8080}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
    allowed-methods: ${APP_CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${APP_CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${APP_CORS_ALLOW_CREDENTIALS:true}
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${JWT_EXP_ACCESS:15m}
    refresh-expiration: ${JWT_EXP_REFRESH:7d}

#logging:
#  level:
#    sql: debug
#    root: debug
#    web: debug
